import { NETWORK_CONFIGS } from './config';
export const NETWORKS = {
  ETHEREUM: 'ETHEREUM',
  POLYGON: 'POLYGON',
};

export const DEFAULT_NETWORK = NETWORKS.POLYGON;

export const CHAIN_ID = {};
CHAIN_ID[NETWORKS.ETHEREUM] =
  NETWORK_CONFIGS[DEFAULT_NETWORK][
    process.env.REACT_APP_BLOCKCHAIN_NETWORK
  ].CHAIN_ID;
CHAIN_ID[NETWORKS.POLYGON] =
  NETWORK_CONFIGS[DEFAULT_NETWORK][
    process.env.REACT_APP_BLOCKCHAIN_NETWORK
  ].CHAIN_ID;

export const CHAIN_NAME = {};
CHAIN_NAME[NETWORKS.ETHEREUM] =
  NETWORK_CONFIGS[DEFAULT_NETWORK][
    process.env.REACT_APP_BLOCKCHAIN_NETWORK
  ].CHAIN_NAME;
CHAIN_NAME[NETWORKS.POLYGON] =
  NETWORK_CONFIGS[DEFAULT_NETWORK][
    process.env.REACT_APP_BLOCKCHAIN_NETWORK
  ].CHAIN_NAME;

export const RPC_URL = {};
RPC_URL[NETWORKS.ETHEREUM] =
  NETWORK_CONFIGS[DEFAULT_NETWORK][
    process.env.REACT_APP_BLOCKCHAIN_NETWORK
  ].RPC;
RPC_URL[NETWORKS.POLYGON] =
  NETWORK_CONFIGS[DEFAULT_NETWORK][
    process.env.REACT_APP_BLOCKCHAIN_NETWORK
  ].RPC;

export const BLOCKCHAIN_EXPLORER =
  NETWORK_CONFIGS[DEFAULT_NETWORK][process.env.REACT_APP_BLOCKCHAIN_NETWORK]
    .BLOCKCHAIN_EXPLORER;

export const NATIVE_CURRENCY = {
  ETHEREUM: {
    NATIVE: 'ETH',
    WRAPPED: 'WETH',
  },
  POLYGON: {
    NATIVE: 'MATIC',
    WRAPPED: 'WMATIC',
  },
};
